name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs:
      docker-image-name:
        description: 'Docker Image Name'
        required: true
        default: 'test11111'
      docker-tag:
        description: 'Docker Tag'
        required: true
        default: 'latest1'
jobs:

  build-war:

   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Java Maven
      run: |
        java -version
        mvn -version
    - name: Build with Maven
      run: mvn clean install
    - name: file copy
      run: |
        cp /home/runner/work/docker_build/docker_build/webapp/target/webapp.war .
        ls -ltr
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.event.inputs.docker-image-name }}:${{ github.event.inputs.docker-tag }}
    - name: show images
      run: |
        docker images
        
